/**
 * progress.js — per-session investigation progress.
 *
 * The session id is generated by the browser and sent with each scoring call,
 * so there is no login and no personal data. The server keeps the
 * authoritative score for that id; the client mirrors it in localStorage so
 * the page still shows a score when the API is not running.
 */

import { Router } from 'express';
import { route } from '../lib/http.js';
import { getSession, resetSession, sessionCount } from '../lib/store.js';
import { summarise } from './cases.js';

const router = Router();

router.get('/:sessionId', route((req, res) => {
  const session = getSession(req.params.sessionId);
  res.json({ session: summarise(session) });
}));

router.post('/:sessionId/reset', route((req, res) => {
  const session = resetSession(req.params.sessionId);
  res.json({ session: summarise(session), reset: true });
}));

router.get('/', route((req, res) => {
  // Aggregate only — no session contents, nothing that identifies anyone.
  res.json({ activeSessions: sessionCount() });
}));

export default router;
